# Generated by Django 5.1.3 on 2024-11-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
