# Generated by Django 5.1.3 on 2024-11-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee_emp_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_employed',
            field=models.BooleanField(default=False),
        ),
    ]
